/*
===============================================================================

 ██╗  ██╗██╗   ██╗ ██████╗
 ██║ ██╔╝██║   ██║██╔═══██╗
 █████╔╝ ██║   ██║██║   ██║
 ██╔═██╗ ██║   ██║██║   ██║
 ██║  ██╗╚██████╔╝╚██████╔╝
 ╚═╝  ╚═╝ ╚═════╝  ╚═════╝

 Kuo Programming Language Compiler
===============================================================================

 Copyright (c) 2026 kuolang.org

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction.
===============================================================================
*/
#include "codegen.h"
#include <stdexcept>
#include <sstream>
#include <iomanip>
#include <cctype>

void CodeGen::pushScope() { scopeStack.emplace_back(); }
void CodeGen::popScope()  { if (!scopeStack.empty()) scopeStack.pop_back(); }

void CodeGen::declareVar(const std::string& name, KuoType type) {
    if (!scopeStack.empty()) scopeStack.back()[name] = type;
}

KuoType CodeGen::lookupVar(const std::string& name) {
    for (int i = (int)scopeStack.size() - 1; i >= 0; --i) {
        auto it = scopeStack[i].find(name);
        if (it != scopeStack[i].end()) return it->second;
    }
    return KuoType::Unknown;
}

std::string CodeGen::indent() const { return std::string(indentLevel * 4, ' '); }
void CodeGen::emit(const std::string& s)     { out << s; }
void CodeGen::emitLine(const std::string& s) { out << indent() << s << "\n"; }

std::string CodeGen::generate(const Program& prog) {
    out.str(""); out.clear();
    indentLevel = 0;

    emitLine("// Generated by Kuo compiler");
    emitLine("// This should be in your /tmp directory");
    emitLine("// Do not modify it if you don't know what to do");
    emitLine("#include <iostream>");
    emitLine("#include <string>");
    emitLine("#include <cmath>");
    emitLine("");

    // Built-in helpers for string functions used by the core library
    emitLine("static int kuo_len(const std::string& s) { return static_cast<int>(s.size()); }");
    emitLine("static std::string kuo_upper(const std::string& s) {");
    indentLevel++;
    emitLine("std::string r = s;");
    emitLine("for (char& c : r) { c = static_cast<char>(std::toupper(static_cast<unsigned char>(c))); }");
    emitLine("return r;");
    indentLevel--;
    emitLine("}");
    emitLine("static std::string kuo_lower(const std::string& s) {");
    indentLevel++;
    emitLine("std::string r = s;");
    emitLine("for (char& c : r) { c = static_cast<char>(std::tolower(static_cast<unsigned char>(c))); }");
    emitLine("return r;");
    indentLevel--;
    emitLine("}");
    emitLine("static bool kuo_contains(const std::string& s, const std::string& sub) {");
    indentLevel++;
    emitLine("return s.find(sub) != std::string::npos;");
    indentLevel--;
    emitLine("}");
    emitLine("static std::string kuo_split_first(const std::string& s, const std::string& sep) {");
    indentLevel++;
    emitLine("std::size_t pos = s.find(sep);");
    emitLine("if (pos == std::string::npos) return s;");
    emitLine("return s.substr(0, pos);");
    indentLevel--;
    emitLine("}");
    emitLine("");

    for (const auto& s : prog.stmts) {
        if (auto* f = dynamic_cast<const FuncDeclStmt*>(s.get())) {
            funcReturnTypes[f->name] = f->returnType;
        }
    }

    bool hasFuncs = false;
    for (const auto& s : prog.stmts) {
        if (auto* f = dynamic_cast<const FuncDeclStmt*>(s.get())) {
            hasFuncs = true;
            out << kuoTypeToCpp(f->returnType) << " " << f->name << "(";
            for (size_t i = 0; i < f->params.size(); ++i) {
                if (i) out << ", ";
                out << kuoTypeToCpp(f->params[i].type) << " " << f->params[i].name;
            }
            out << ");\n";
        }
    }
    if (hasFuncs) emitLine("");

    for (const auto& s : prog.stmts) {
        if (dynamic_cast<const FuncDeclStmt*>(s.get())) {
            genStmt(s.get());
        }
    }

    emitLine("int main() {");
    indentLevel++;
    pushScope();

    for (const auto& s : prog.stmts) {
        if (!dynamic_cast<const FuncDeclStmt*>(s.get())) {
            genStmt(s.get());
        }
    }

    emitLine("return 0;");
    popScope();
    indentLevel--;
    emitLine("}");

    return out.str();
}

void CodeGen::genStmt(const Stmt* s) {
    if (auto* n = dynamic_cast<const VarDeclStmt*>(s))   { genVarDecl(n); return; }
    if (auto* n = dynamic_cast<const FuncDeclStmt*>(s))  { genFuncDecl(n); return; }
    if (auto* n = dynamic_cast<const BlockStmt*>(s))     { genBlock(n); return; }
    if (auto* n = dynamic_cast<const IfStmt*>(s))        { genIf(n); return; }
    if (auto* n = dynamic_cast<const WhileStmt*>(s))     { genWhile(n); return; }
    if (auto* n = dynamic_cast<const ForStmt*>(s))       { genFor(n); return; }
    if (auto* n = dynamic_cast<const ReturnStmt*>(s))    { genReturn(n); return; }
    if (auto* n = dynamic_cast<const PrintStmt*>(s))     { genPrint(n); return; }
    if (auto* n = dynamic_cast<const ExprStmt*>(s))      { genExprStmt(n); return; }
    if (auto* n = dynamic_cast<const BreakStmt*>(s))     { genBreak(n); return; }
    if (auto* n = dynamic_cast<const ContinueStmt*>(s))  { genContinue(n); return; }
    throw std::runtime_error("Unknown statement type in codegen");
}

void CodeGen::genVarDecl(const VarDeclStmt* s) {
    KuoType type = s->type;
    // Type inference
    if (type == KuoType::Unknown && s->init) {
        type = inferType(s->init.get());
    }
    if (type == KuoType::Unknown) type = KuoType::Int; // fallback variable, TODO: Throw exception instead of giving integer

    declareVar(s->name, type);

    out << indent() << kuoTypeToCpp(type) << " " << s->name;
    if (s->init) {
        out << " = " << genExpr(s->init.get());
    }
    out << ";\n";
}

void CodeGen::genFuncDecl(const FuncDeclStmt* s) {
    out << kuoTypeToCpp(s->returnType) << " " << s->name << "(";
    for (size_t i = 0; i < s->params.size(); ++i) {
        if (i) out << ", ";
        out << kuoTypeToCpp(s->params[i].type) << " " << s->params[i].name;
    }
    out << ") ";
    pushScope();
    for (auto& p : s->params) declareVar(p.name, p.type);
    genBlock(s->body.get(), false);
    popScope();
    out << "\n";
}

void CodeGen::genBlock(const BlockStmt* s, bool pushScopeHere) {
    emitLine("{");
    indentLevel++;
    if (pushScopeHere) pushScope();
    for (const auto& stmt : s->stmts) genStmt(stmt.get());
    if (pushScopeHere) popScope();
    indentLevel--;
    emit(indent() + "}");
    out << "\n";
}

void CodeGen::genIf(const IfStmt* s) {
    out << indent() << "if (" << genExpr(s->condition.get()) << ") ";
    if (auto* b = dynamic_cast<const BlockStmt*>(s->thenBranch.get())) {
        pushScope();
        genBlock(b, false);
        popScope();
    } else {
        out << "\n";
        indentLevel++;
        genStmt(s->thenBranch.get());
        indentLevel--;
    }
    if (s->elseBranch) {
        out << indent() << "else ";
        if (auto* b = dynamic_cast<const BlockStmt*>(s->elseBranch.get())) {
            pushScope();
            genBlock(b, false);
            popScope();
        } else {
            out << "\n";
            indentLevel++;
            genStmt(s->elseBranch.get());
            indentLevel--;
        }
    }
}

void CodeGen::genWhile(const WhileStmt* s) {
    out << indent() << "while (" << genExpr(s->condition.get()) << ") ";
    if (auto* b = dynamic_cast<const BlockStmt*>(s->body.get())) {
        pushScope();
        genBlock(b, false);
        popScope();
    } else {
        out << "\n";
        indentLevel++;
        genStmt(s->body.get());
        indentLevel--;
    }
}

void CodeGen::genFor(const ForStmt* s) {
    out << indent() << "for (";
    pushScope();

    // init
    if (s->init) {
        if (auto* vd = dynamic_cast<const VarDeclStmt*>(s->init.get())) {
            KuoType type = vd->type;
            if (type == KuoType::Unknown && vd->init) type = inferType(vd->init.get());
            if (type == KuoType::Unknown) type = KuoType::Int;
            declareVar(vd->name, type);
            out << kuoTypeToCpp(type) << " " << vd->name;
            if (vd->init) out << " = " << genExpr(vd->init.get());
        } else if (auto* es = dynamic_cast<const ExprStmt*>(s->init.get())) {
            out << genExpr(es->expr.get());
        }
    }
    out << "; ";

    if (s->condition) out << genExpr(s->condition.get());
    out << "; ";

    if (s->update) out << genExpr(s->update.get());
    out << ") ";

    if (auto* b = dynamic_cast<const BlockStmt*>(s->body.get())) {
        genBlock(b, false);
    } else {
        out << "\n";
        indentLevel++;
        genStmt(s->body.get());
        indentLevel--;
    }
    popScope();
}

void CodeGen::genBreak(const BreakStmt* s) {
    emitLine("break;");
}

void CodeGen::genContinue(const ContinueStmt* s) {
    emitLine("continue;");
}

void CodeGen::genReturn(const ReturnStmt* s) {
    if (s->value) {
        emitLine("return " + genExpr(s->value.get()) + ";");
    } else {
        emitLine("return;");
    }
}

void CodeGen::genPrint(const PrintStmt* s) {
    KuoType t = inferType(s->value.get());
    if (t == KuoType::Bool) {
        emitLine("std::cout << std::boolalpha << " + genExpr(s->value.get()) + " << std::endl;");
    } else {
        emitLine("std::cout << " + genExpr(s->value.get()) + " << std::endl;");
    }
}

void CodeGen::genExprStmt(const ExprStmt* s) {
    emitLine(genExpr(s->expr.get()) + ";");
}

std::string CodeGen::genExpr(const Expr* e) {
    if (auto* n = dynamic_cast<const IntLitExpr*>(e))    return std::to_string(n->value);
    if (auto* n = dynamic_cast<const FloatLitExpr*>(e)) {
        std::ostringstream ss;
        ss << std::setprecision(15) << n->value;
        std::string s = ss.str();
        if (s.find('.') == std::string::npos && s.find('e') == std::string::npos)
            s += ".0";
        return s;
    }
    if (auto* n = dynamic_cast<const BoolLitExpr*>(e))   return n->value ? "true" : "false";
    if (auto* n = dynamic_cast<const StringLitExpr*>(e)) {
        std::string r = "\"";
        for (char c : n->value) {
            if (c == '"')  r += "\\\"";
            else if (c == '\\') r += "\\\\";
            else if (c == '\n') r += "\\n";
            else if (c == '\t') r += "\\t";
            else r += c;
        }
        r += "\"";
        return r;
    }
    if (auto* n = dynamic_cast<const IdentExpr*>(e))    return n->name;
    if (auto* n = dynamic_cast<const BinaryExpr*>(e))   return genBinary(n);
    if (auto* n = dynamic_cast<const UnaryExpr*>(e))    return genUnary(n);
    if (auto* n = dynamic_cast<const CallExpr*>(e))     return genCall(n);
    if (auto* n = dynamic_cast<const AssignExpr*>(e))   return genAssign(n);
    if (auto* n = dynamic_cast<const PostfixExpr*>(e))  return genPostfix(n);
    throw std::runtime_error("Unknown expression type in codegen");
}

std::string CodeGen::genBinary(const BinaryExpr* e) {
    if (e->op == "+") {
        KuoType lt = inferType(e->left.get());
        KuoType rt = inferType(e->right.get());
        bool leftIsStr  = (lt == KuoType::String);
        bool rightIsStr = (rt == KuoType::String);
        if (leftIsStr || rightIsStr) {
            auto wrapIfNeeded = [&](const Expr* ex, KuoType t) -> std::string {
                std::string s = genExpr(ex);
                if (t == KuoType::String) return s;
                if (t == KuoType::Bool)   return "(std::string(" + s + " ? \"true\" : \"false\"))";
                return "std::to_string(" + s + ")";
            };
            return "(" + wrapIfNeeded(e->left.get(), lt) + " + " + wrapIfNeeded(e->right.get(), rt) + ")";
        }
    }
    return "(" + genExpr(e->left.get()) + " " + e->op + " " + genExpr(e->right.get()) + ")";
}

std::string CodeGen::genUnary(const UnaryExpr* e) {
    return "(" + e->op + genExpr(e->operand.get()) + ")";
}

std::string CodeGen::genCall(const CallExpr* e) {
    if (e->callee == "len" && e->args.size() == 1) {
        KuoType t = inferType(e->args[0].get());
        if (t != KuoType::String) {
            throw std::runtime_error("len() expects a string argument");
        }
        return "kuo_len(" + genExpr(e->args[0].get()) + ")";
    }
    if (e->callee == "upper" && e->args.size() == 1) {
        KuoType t = inferType(e->args[0].get());
        if (t != KuoType::String) {
            throw std::runtime_error("upper() expects a string argument");
        }
        return "kuo_upper(" + genExpr(e->args[0].get()) + ")";
    }
    if (e->callee == "lower" && e->args.size() == 1) {
        KuoType t = inferType(e->args[0].get());
        if (t != KuoType::String) {
            throw std::runtime_error("lower() expects a string argument");
        }
        return "kuo_lower(" + genExpr(e->args[0].get()) + ")";
    }
    if (e->callee == "contains" && e->args.size() == 2) {
        KuoType t0 = inferType(e->args[0].get());
        KuoType t1 = inferType(e->args[1].get());
        if (t0 != KuoType::String || t1 != KuoType::String) {
            throw std::runtime_error("contains() expects two string arguments");
        }
        return "kuo_contains(" + genExpr(e->args[0].get()) + ", " + genExpr(e->args[1].get()) + ")";
    }
    if (e->callee == "split" && e->args.size() == 2) {
        // For now, split returns the substring before the first occurrence of the separator.
        KuoType t0 = inferType(e->args[0].get());
        KuoType t1 = inferType(e->args[1].get());
        if (t0 != KuoType::String || t1 != KuoType::String) {
            throw std::runtime_error("split() expects two string arguments");
        }
        return "kuo_split_first(" + genExpr(e->args[0].get()) + ", " + genExpr(e->args[1].get()) + ")";
    }

    std::string s = e->callee + "(";
    for (size_t i = 0; i < e->args.size(); ++i) {
        if (i) s += ", ";
        s += genExpr(e->args[i].get());
    }
    s += ")";
    return s;
}

std::string CodeGen::genAssign(const AssignExpr* e) {
    return e->name + " " + e->op + " " + genExpr(e->value.get());
}

std::string CodeGen::genPostfix(const PostfixExpr* e) {
    return e->name + e->op;
}

KuoType CodeGen::inferType(const Expr* e) {
    if (dynamic_cast<const IntLitExpr*>(e))    return KuoType::Int;
    if (dynamic_cast<const FloatLitExpr*>(e))  return KuoType::Float;
    if (dynamic_cast<const BoolLitExpr*>(e))   return KuoType::Bool;
    if (dynamic_cast<const StringLitExpr*>(e)) return KuoType::String;

    if (auto* n = dynamic_cast<const IdentExpr*>(e)) {
        return lookupVar(n->name);
    }
    if (auto* n = dynamic_cast<const BinaryExpr*>(e)) {
        if (n->op == "==" || n->op == "!=" || n->op == "<" || n->op == ">" ||
            n->op == "<=" || n->op == ">=" || n->op == "&&" || n->op == "||")
            return KuoType::Bool;
        KuoType l = inferType(n->left.get());
        KuoType r = inferType(n->right.get());
        if (l == KuoType::Float || r == KuoType::Float) return KuoType::Float;
        if (l == KuoType::String || r == KuoType::String) return KuoType::String;
        return l;
    }
    if (auto* n = dynamic_cast<const UnaryExpr*>(e)) {
        if (n->op == "!") return KuoType::Bool;
        return inferType(n->operand.get());
    }
    if (auto* n = dynamic_cast<const CallExpr*>(e)) {
        // Built-in string functions
        if (n->callee == "len")      return KuoType::Int;
        if (n->callee == "upper")    return KuoType::String;
        if (n->callee == "lower")    return KuoType::String;
        if (n->callee == "contains") return KuoType::Bool;
        if (n->callee == "split")    return KuoType::String; // first segment before separator

        auto it = funcReturnTypes.find(n->callee);
        if (it != funcReturnTypes.end()) return it->second;
        return KuoType::Unknown;
    }
    if (auto* n = dynamic_cast<const AssignExpr*>(e)) {
        return lookupVar(n->name);
    }
    return KuoType::Unknown;
}
